# Site settings
title: Top dead center
email: deepankar.bhardwaj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        A nerd's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deepankarb.github.io/" # the base hostname & protocol for your site
twitter_username: deepankarb
github_username:  deepankarb

# Build settings
markdown: kramdown
